//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_02CATPROV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_02CATPROV()
        {
            this.SIDEPS_03CATCANT = new HashSet<SIDEPS_03CATCANT>();
        }
    
        public int CODPROV02 { get; set; }
        public string NOMPROV02 { get; set; }
        public Nullable<int> CODPAIS01 { get; set; }
    
        public virtual SIDEPS_01CATPAIS SIDEPS_01CATPAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_03CATCANT> SIDEPS_03CATCANT { get; set; }
    }
}
