//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_08REGTELF
    {
        public int CODTELF08 { get; set; }
        public string CEDUSRO07 { get; set; }
        public string NUMTELF08 { get; set; }
    
        public virtual SIDEPS_07REGUSRO SIDEPS_07REGUSRO { get; set; }
    }
}
