//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_03CATCANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_03CATCANT()
        {
            this.SIDEPS_04REGDIAC = new HashSet<SIDEPS_04REGDIAC>();
            this.SIDEPS_07REGUSRO = new HashSet<SIDEPS_07REGUSRO>();
            this.SIDEPS_13REGPERS = new HashSet<SIDEPS_13REGPERS>();
        }
    
        public int CODCANT03 { get; set; }
        public string NOMCANT03 { get; set; }
        public Nullable<int> CODPROV02 { get; set; }
    
        public virtual SIDEPS_02CATPROV SIDEPS_02CATPROV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_04REGDIAC> SIDEPS_04REGDIAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_07REGUSRO> SIDEPS_07REGUSRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_13REGPERS> SIDEPS_13REGPERS { get; set; }
    }
}
