//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_28REGHIS
    {
        public int CODHIST28 { get; set; }
        public Nullable<int> CODCASO25 { get; set; }
        public string DESCASO28 { get; set; }
        public string ESTCASO28 { get; set; }
        public Nullable<System.DateTime> FECCASO28 { get; set; }
        public Nullable<System.DateTime> FECACTU28 { get; set; }
    
        public virtual SIDEPS_25REGCASO SIDEPS_25REGCASO { get; set; }
    }
}
