BEGIN TRY
BEGIN TRAN
	--IMPORTAR RELIGION
	insert into SIDEPS.dbo.SIDEPS_11CATRELG(DESRELG11)
	select DESRELG11 from SIDEPSDaniela.dbo.SIDEPS_11CATRELG

	--IMPORTAR CANTONES
	insert into SIDEPS.dbo.SIDEPS_03CATCANT(NOMCANT03)
	select NOMCANT03 from SIDEPSDaniela.dbo.SIDEPS_03CATCANT

	--IMPORTAR ESCOLARIDAD
	insert into SIDEPS.dbo.SIDEPS_09CATNEDU(DESNEDU09)
	select DESNEDU09 from SIDEPSDaniela.dbo.SIDEPS_09CATNEDU

	--IMPORTAR ESTADO CIVIL
	insert into SIDEPS.dbo.SIDEPS_06CATESTC(DESESTC06)
	select DESESTC06 from SIDEPSDaniela.dbo.SIDEPS_06CATESTC

	
	insert into SIDEPS.dbo.SIDEPS_01CATPAIS (NOMPAIS01)
	select NOMPAIS01 from SIDEPSDaniela.dbo.SIDEPS_01CATPAIS
	

	insert into SIDEPS.dbo.SIDEPS_02CATPROV (NOMPROV02, CODPAIS01)
	select NOMPROV02, CODPAIS01 from SIDEPSDaniela.dbo.SIDEPS_02CATPROV
	

	insert into SIDEPS.dbo.SIDEPS_05TIPUSRO (DESUSRO05)
	select DESUSRO05 from SIDEPSDaniela.dbo.SIDEPS_05TIPUSRO
	

	insert into SIDEPS.dbo.SIDEPS_10CATSOLI (DESSOLI10)
	select DESSOLI10 from SIDEPSDaniela.dbo.SIDEPS_10CATSOLI
	

	insert into SIDEPS.dbo.SIDEPS_12CATPARE (DESPARE12)
	select DESPARE12 from SIDEPSDaniela.dbo.SIDEPS_12CATPARE
	

	insert into SIDEPS.dbo.SIDEPS_14CATSEGU (DESSEGU14)
	select DESSEGU14 from SIDEPSDaniela.dbo.SIDEPS_14CATSEGU
	

	insert into SIDEPS.dbo.SIDEPS_15CATENFR (DESENFR15)
	select DESENFR15 from SIDEPSDaniela.dbo.SIDEPS_15CATENFR
	

	insert into SIDEPS.dbo.SIDEPS_17CATMATE (DESMATE17)
	select DESMATE17 from SIDEPSDaniela.dbo.SIDEPS_17CATMATE
	

	insert into SIDEPS.dbo.SIDEPS_18TIPVIVI (DESTIPV18)
	select DESTIPV18 from SIDEPSDaniela.dbo.SIDEPS_18TIPVIVI
	

	insert into SIDEPS.dbo.SIDEPS_19ESTVIVI (DESESTV19)
	select DESESTV19 from SIDEPSDaniela.dbo.SIDEPS_19ESTVIVI
	

	insert into SIDEPS.dbo.SIDEPS_21CATORGS (DESORGS21)
	select DESORGS21 from SIDEPSDaniela.dbo.SIDEPS_21CATORGS
	

	insert into SIDEPS.dbo.SIDEPS_26CATAYUD (DESAYUD26)
	select DESAYUD26 from SIDEPSDaniela.dbo.SIDEPS_26CATAYUD
	

	insert into SIDEPS.dbo.SIDEPS_27TIPAYUD (CODAYUD26, CODCASO25)
	select CODAYUD26, CODCASO25 from SIDEPSDaniela.dbo.SIDEPS_27TIPAYUD


COMMIT
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH