BEGIN TRY
BEGIN TRAN
	--IMPORTAR RELIGION
	insert into SIDEPS.dbo.SIDEPS_11CATRELG(DESRELG11)
	select DESRELG11 from SIDEPSDaniela.dbo.SIDEPS_11CATRELG

	--IMPORTAR CANTONES
	insert into SIDEPS.dbo.SIDEPS_03CATCANT(NOMCANT03)
	select NOMCANT03 from SIDEPSDaniela.dbo.SIDEPS_03CATCANT

	--IMPORTAR ESCOLARIDAD
	insert into SIDEPS.dbo.SIDEPS_09CATNEDU(DESNEDU09)
	select DESNEDU09 from SIDEPSDaniela.dbo.SIDEPS_09CATNEDU

	--IMPORTAR ESTADO CIVIL
	insert into SIDEPS.dbo.SIDEPS_06CATESTC(DESESTC06)
	select DESESTC06 from SIDEPSDaniela.dbo.SIDEPS_06CATESTC


COMMIT
END TRY
BEGIN CATCH
	ROLLBACK
END CATCH