USE [SIDEPS]
GO
/****** Object:  StoredProcedure [dbo].[SP_CON_REGDIAC]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_CON_REGDIAC') IS NOT NULL DROP PROCEDURE SP_CON_REGDIAC
GO
CREATE PROCEDURE [dbo].[SP_CON_REGDIAC]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_04REGDIAC]
END
GO
/****** Object:  StoredProcedure [dbo].[SP_CON_REGUSRO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_CON_REGUSRO') IS NOT NULL DROP PROCEDURE SP_CON_REGUSRO
GO
CREATE PROCEDURE [dbo].[SP_CON_REGUSRO]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_07REGUSRO]
END
GO
/****** Object:  StoredProcedure [dbo].[SP_CONXID_REGDIAC]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_CONXID_REGDIAC') IS NOT NULL DROP PROCEDURE SP_CONXID_REGDIAC
GO
CREATE PROCEDURE [dbo].[SP_CONXID_REGDIAC]
@CODDIAC04 INT
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_04REGDIAC]
WHERE CODDIAC04 = @CODDIAC04
END
GO
/****** Object:  StoredProcedure [dbo].[SP_CONXID_REGUSRO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_CONXID_REGUSRO') IS NOT NULL DROP PROCEDURE SP_CONXID_REGUSRO
GO
CREATE PROCEDURE [dbo].[SP_CONXID_REGUSRO]
@CEDUSRO07 INT
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_07REGUSRO]
WHERE CEDUSRO07 = @CEDUSRO07
END
GO
/****** Object:  StoredProcedure [dbo].[SP_DEL_REGDIAC]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_DEL_REGDIAC') IS NOT NULL DROP PROCEDURE SP_DEL_REGDIAC
GO
CREATE PROCEDURE [dbo].[SP_DEL_REGDIAC]
@CODDIAC04 INT

AS
BEGIN
UPDATE SIDEPS_04REGDIAC
SET ESTDIAC04 = 'INACTIVO'
WHERE CODDIAC04 = @CODDIAC04

END
GO
/****** Object:  StoredProcedure [dbo].[SP_DEL_REGUSRO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_DEL_REGUSRO') IS NOT NULL DROP PROCEDURE SP_DEL_REGUSRO
GO
CREATE PROCEDURE [dbo].[SP_DEL_REGUSRO]
@CEDUSRO07 VARCHAR(20)


AS
BEGIN
UPDATE SIDEPS_07REGUSRO
SET ESTUSRO07 = 'INACTIVO', FEFUSRO07 = GETDATE()
WHERE CEDUSRO07 = @CEDUSRO07

END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGASPS]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGASPS') IS NOT NULL DROP PROCEDURE SP_INS_REGASPS
GO
CREATE PROCEDURE [dbo].[SP_INS_REGASPS]
		 @CEDPERS13 varchar(20)
		,@CODSEGU14 int
		,@CODENFR15 int
		,@DESENFR16 varchar(50)
		,@RECTRAT16 varchar(2)
		,@DESTRAT16 varchar(50)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_16REGASPS
    (
		 CEDPERS13
		,CODSEGU14
		,CODENFR15
		,DESENFR16
		,RECTRAT16
		,DESTRAT16
	)
    VALUES (
		 @CEDPERS13
		,@CODSEGU14
		,@CODENFR15
		,@DESENFR16
		,@RECTRAT16
		,@DESTRAT16
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGCASO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGCASO') IS NOT NULL DROP PROCEDURE SP_INS_REGCASO
GO
CREATE PROCEDURE [dbo].[SP_INS_REGCASO]
		 @CEDPERS13 varchar(20)
		,@CODASPS16 int
		,@CEDUSRO07 varchar(20)
		,@CODVIVI20 int
		,@CODEGRF24 int
		,@FEICASO25 datetime
		,@FEFCASO25 datetime
		,@DESCASO25 varchar(200)
		,@OPICASO25 varchar(200)
		,@ESTCASO25 varchar(20)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_25REGCASO
    (
		 CEDPERS13
		,CODASPS16
		,CEDUSRO07
		,CODVIVI20
		,CODEGRF24
		,FEICASO25
		,FEFCASO25
		,DESCASO25
		,OPICASO25
		,ESTCASO25
	)
    VALUES 
	(
		 @CEDPERS13
		,@CODASPS16
		,@CEDUSRO07
		,@CODVIVI20
		,@CODEGRF24
		,@FEICASO25
		,@FEFCASO25
		,@DESCASO25
		,@OPICASO25
		,@ESTCASO25
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGDIAC]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGDIAC') IS NOT NULL DROP PROCEDURE SP_INS_REGDIAC
GO
CREATE  PROCEDURE [dbo].[SP_INS_REGDIAC]
@NOMDIAC04 VARCHAR(50),
@LUGDIAC04 VARCHAR(100),
@TELDIAC04 VARCHAR(12),
@CODCANT03 INT
AS
BEGIN

INSERT INTO SIDEPS_04REGDIAC ( NOMDIAC04 ,LUGDIAC04 ,TELDIAC04 ,ESTDIAC04,CODCANT03 )
VALUES (@NOMDIAC04 ,@LUGDIAC04 ,@TELDIAC04 ,'ACTIVO',@CODCANT03 )
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGEGRF]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGEGRF') IS NOT NULL DROP PROCEDURE SP_INS_REGEGRF
GO
CREATE PROCEDURE [dbo].[SP_INS_REGEGRF]
		 @MTOALQU24 decimal(18,4)
		,@MTOALIM24 decimal(18,4)
		,@MTOELEC24 decimal(18,4)
		,@MTOGAST24 decimal(18,4)
		,@MTCAGUA24 decimal(18,4)
		,@MTOCABL24 decimal(18,4)
		,@MTOTELF24 decimal(18,4)
		,@MTOINTE24 decimal(18,4)
		,@MTOEDUC24 decimal(18,4)
		,@MTOSEGU24 decimal(18,4)
		,@MTOOTRO24 decimal(18,4)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_24REGEGRF
    (
		 MTOALQU24
		,MTOALIM24
		,MTOELEC24
		,MTOGAST24
		,MTCAGUA24
		,MTOCABL24
		,MTOTELF24
		,MTOINTE24
		,MTOEDUC24
		,MTOSEGU24
		,MTOOTRO24
	)
    VALUES 
	(			
		 @MTOALQU24
		,@MTOALIM24
		,@MTOELEC24
		,@MTOGAST24
		,@MTCAGUA24
		,@MTOCABL24
		,@MTOTELF24
		,@MTOINTE24
		,@MTOEDUC24
		,@MTOSEGU24
		,@MTOOTRO24
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGFAML]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGFAML') IS NOT NULL DROP PROCEDURE SP_INS_REGFAML
GO
CREATE PROCEDURE [dbo].[SP_INS_REGFAML]
		 @CEDFAML22 varchar(20)
		,@NOMFAML22 varchar(50)
		,@EDAFAML22 int
		,@CODESTC06 int
		,@CODNEDU09 int
		,@OACFAML22 varchar(100)
		,@INGFAML22 decimal(18,4)
		,@DESFAML22 varchar(200)
		,@CODORGS21 int
		,@CODENFR15 int
		,@CODPARE12 int
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_22REGFAML
    (
		 CEDFAML22
		,NOMFAML22
		,EDAFAML22
		,CODESTC06
		,CODNEDU09
		,OACFAML22
		,INGFAML22
		,DESFAML22
		,CODORGS21
		,CODENFR15
		,CODPARE12
	)
    VALUES 
	(
		 @CEDFAML22
		,@NOMFAML22
		,@EDAFAML22
		,@CODESTC06
		,@CODNEDU09
		,@OACFAML22
		,@INGFAML22
		,@DESFAML22
		,@CODORGS21
		,@CODENFR15
		,@CODPARE12
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGPERS]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGPERS') IS NOT NULL DROP PROCEDURE SP_INS_REGPERS
GO
CREATE PROCEDURE [dbo].[SP_INS_REGPERS]
		 @CEDPERS13 varchar(20)
		,@CODESTC06 int
		,@CODNEDU09 int
		,@CODCANT03 int
		,@CODSOLI10 int
		,@CODRELG11 int
		,@NOMPERS13 varchar(20)
		,@PAPPERS13 varchar(20)
		,@SAPPERS13 varchar(20)
		,@NACPERS13 varchar(50)
		,@DIRPERS13 varchar(200)
		,@OACPERS13 varchar(100)
		,@OANPERS13 varchar(100)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_13REGPERS
    (
		 CEDPERS13
        ,CODESTC06
        ,CODNEDU09
        ,CODCANT03
        ,CODSOLI10
        ,CODRELG11
        ,NOMPERS13
        ,PAPPERS13
        ,SAPPERS13
        ,NACPERS13
        ,DIRPERS13
        ,OACPERS13
        ,OANPERS13
	)
    VALUES
	(
		 @CEDPERS13
		,@CODESTC06
		,@CODNEDU09
		,@CODCANT03
		,@CODSOLI10
		,@CODRELG11
		,@NOMPERS13
		,@PAPPERS13
		,@SAPPERS13
		,@NACPERS13
		,@DIRPERS13
		,@OACPERS13
		,@OANPERS13
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGUSRO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGUSRO') IS NOT NULL DROP PROCEDURE SP_INS_REGUSRO
GO
CREATE  PROCEDURE [dbo].[SP_INS_REGUSRO]
@CEDUSRO07 VARCHAR(20),
@NOMUSRO07 VARCHAR(50),
@PAPUSRO07 VARCHAR(50),
@SAPUSRO07 VARCHAR(50),
@CODCANT03 INT,
@CODDIAC04 INT,
@CODUSRO05 INT,
@DIRUSRO07 VARCHAR(200),
@NACUSRO07 VARCHAR(15),
@CNTUSRO07 VARCHAR(30),
@FENUSRO07 DATETIME
AS
BEGIN

INSERT INTO SIDEPS_07REGUSRO
(CEDUSRO07,NOMUSRO07,PAPUSRO07,SAPUSRO07,CODCANT03,CODDIAC04,CODUSRO05,ESTUSRO07,DIRUSRO07,NACUSRO07,CNTUSRO07,FEIUSRO07,FEFUSRO07,FENUSRO07)
VALUES(
@CEDUSRO07, @NOMUSRO07, @PAPUSRO07, @SAPUSRO07,@CODCANT03, @CODDIAC04, @CODUSRO05,'ACTIVO', @DIRUSRO07, @NACUSRO07, @CNTUSRO07, GETDATE(), '9999-12-12',
@FENUSRO07)
END
GO
/****** Object:  StoredProcedure [dbo].[SP_INS_REGVIVI]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_INS_REGVIVI') IS NOT NULL DROP PROCEDURE SP_INS_REGVIVI
GO
CREATE PROCEDURE [dbo].[SP_INS_REGVIVI]
		 @CODTIPV18 int
        ,@CODESTV19 int
        ,@CODMATE17 int
        ,@MTOVIVI20 decimal(18,4)
        ,@NAPVIVI20 varchar(20)
        ,@SRCVIVI20 varchar(2)
        ,@SRIVIVI20 varchar(2)
        ,@SRLVIVI20 varchar(2)
        ,@SRMVIVI20 varchar(2)
        ,@SRBVIVI20 varchar(2)
        ,@SREVIVI20 varchar(2)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_20REGVIVI
    (
		 CODTIPV18
		,CODESTV19
		,CODMATE17
		,MTOVIVI20
		,NAPVIVI20
		,SRCVIVI20
		,SRIVIVI20
		,SRLVIVI20
		,SRMVIVI20
		,SRBVIVI20
		,SREVIVI20
	)
    VALUES (
		 @CODTIPV18
		,@CODESTV19
		,@CODMATE17
		,@MTOVIVI20
		,@NAPVIVI20
		,@SRCVIVI20
		,@SRIVIVI20
		,@SRLVIVI20
		,@SRMVIVI20
		,@SRBVIVI20
		,@SREVIVI20
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO
/****** Object:  StoredProcedure [dbo].[SP_MOD_REGDIAC]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_MOD_REGDIAC') IS NOT NULL DROP PROCEDURE SP_MOD_REGDIAC
GO
CREATE PROCEDURE [dbo].[SP_MOD_REGDIAC]
@CODDIAC04 INT,
@NOMDIAC04 VARCHAR(50),
@LUGDIAC04 VARCHAR(100),
@TELDIAC04 VARCHAR(12),
@ESTDIAC04 VARCHAR(20),
@CODCANT03 INT
AS
BEGIN
UPDATE SIDEPS_04REGDIAC
SET NOMDIAC04 = @NOMDIAC04, LUGDIAC04 = @LUGDIAC04, TELDIAC04 = @TELDIAC04, ESTDIAC04 = @ESTDIAC04, CODCANT03 = @CODCANT03
WHERE CODDIAC04 = @CODDIAC04

END
GO
/****** Object:  StoredProcedure [dbo].[SP_MOD_REGUSRO]    Script Date: 11/13/2020 12:17:05 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF object_id('SP_MOD_REGUSRO') IS NOT NULL DROP PROCEDURE SP_MOD_REGUSRO
GO
CREATE PROCEDURE [dbo].[SP_MOD_REGUSRO]
@CEDUSRO07 VARCHAR(20),
@NOMUSRO07 VARCHAR(50),
@PAPUSRO07 VARCHAR(50),
@SAPUSRO07 VARCHAR(50),
@CODCANT03 INT,
@CODDIAC04 INT,
@CODUSRO05 INT,
@ESTUSRO07 VARCHAR(20),
@DIRUSRO07 VARCHAR(200),
@NACUSRO07 VARCHAR(15),
@CNTUSRO07 VARCHAR(30),
@FENUSRO07 DATETIME

AS
BEGIN
UPDATE SIDEPS_07REGUSRO
SET NOMUSRO07 = @NOMUSRO07, PAPUSRO07 = @PAPUSRO07, SAPUSRO07 = @SAPUSRO07,CODCANT03 = @CODCANT03,CODDIAC04=@CODDIAC04,CODUSRO05=@CODUSRO05,ESTUSRO07=@ESTUSRO07,
DIRUSRO07=@DIRUSRO07,NACUSRO07=@NACUSRO07,CNTUSRO07=@CNTUSRO07,FENUSRO07=@FENUSRO07
WHERE CEDUSRO07 = @CEDUSRO07

END
GO

IF object_id('SP_CON_CATRELG') IS NOT NULL DROP PROCEDURE SP_CON_CATRELG
GO
CREATE PROCEDURE [dbo].[SP_CON_CATRELG]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_11CATRELG]
END
GO

--estadocivil
IF object_id('SP_CON_CATESTC') IS NOT NULL DROP PROCEDURE SP_CON_CATESTC
GO
CREATE PROCEDURE [dbo].[SP_CON_CATESTC]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_06CATESTC]
END
GO

--escolaridad
IF object_id('SP_CON_CATNEDU') IS NOT NULL DROP PROCEDURE SP_CON_CATNEDU
GO
CREATE PROCEDURE [dbo].[SP_CON_CATNEDU]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_09CATNEDU]
END
GO

--canton
IF object_id('SP_CON_CATCANT') IS NOT NULL DROP PROCEDURE SP_CON_CATCANT
GO
CREATE PROCEDURE [dbo].[SP_CON_CATCANT]
AS
BEGIN
SELECT * FROM [dbo].[SIDEPS_03CATCANT]
END
GO

-- consulta grupo familiar
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF object_id('SP_CON_REGFAML') IS NOT NULL DROP PROCEDURE SP_CON_REGFAML
GO
CREATE PROCEDURE [dbo].[SP_CON_REGFAML](
	@cedulaSolicitante varchar(20)
)
AS
BEGIN
SELECT 
		t22.* 
FROM 
		[dbo].[SIDEPS_22REGFAML] t22
		INNER JOIN [dbo].[SIDEPS_23CATFINA] t23 on
				t22.CEDFAML22 = t23.CEDFAML22

WHERE
		t23.CEDPERS13 = @cedulaSolicitante
END

-- consulta miembro familiar por ID
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF object_id('SP_CONXID_REGFAML') IS NOT NULL DROP PROCEDURE SP_CONXID_REGFAML
GO
CREATE PROCEDURE [dbo].[SP_CONXID_REGFAML](
	@cedula varchar(20)
)
AS
BEGIN
SELECT 
		* 
FROM 
		[dbo].[SIDEPS_22REGFAML]

WHERE
		 CEDFAML22 = @cedula
END
