USE SIDEPS
GO


-- PASO 1: REGISTRO PERSONA
IF object_id('SP_INS_REGPERS') IS NOT NULL DROP PROCEDURE SP_INS_REGPERS
GO
CREATE PROCEDURE SP_INS_REGPERS
		 @CEDPERS13 varchar(20)
		,@CODESTC06 int
		,@CODNEDU09 int
		,@CODCANT03 int
		,@CODSOLI10 int
		,@CODRELG11 int
		,@NOMPERS13 varchar(20)
		,@PAPPERS13 varchar(20)
		,@SAPPERS13 varchar(20)
		,@NACPERS13 varchar(50)
		,@DIRPERS13 varchar(200)
		,@OACPERS13 varchar(100)
		,@OANPERS13 varchar(100)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_13REGPERS
    (
		 CEDPERS13
        ,CODESTC06
        ,CODNEDU09
        ,CODCANT03
        ,CODSOLI10
        ,CODRELG11
        ,NOMPERS13
        ,PAPPERS13
        ,SAPPERS13
        ,NACPERS13
        ,DIRPERS13
        ,OACPERS13
        ,OANPERS13
	)
    VALUES
	(
		 @CEDPERS13
		,@CODESTC06
		,@CODNEDU09
		,@CODCANT03
		,@CODSOLI10
		,@CODRELG11
		,@NOMPERS13
		,@PAPPERS13
		,@SAPPERS13
		,@NACPERS13
		,@DIRPERS13
		,@OACPERS13
		,@OANPERS13
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO


-- PASO 2: REGISTRO ASPECTO SOCIAL
IF object_id('SP_INS_REGASPS') IS NOT NULL DROP PROCEDURE SP_INS_REGASPS
GO
CREATE PROCEDURE SP_INS_REGASPS
		 @CEDPERS13 varchar(20)
		,@CODSEGU14 int
		,@CODENFR15 int
		,@DESENFR16 varchar(50)
		,@RECTRAT16 varchar(2)
		,@DESTRAT16 varchar(50)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_16REGASPS
    (
		 CEDPERS13
		,CODSEGU14
		,CODENFR15
		,DESENFR16
		,RECTRAT16
		,DESTRAT16
	)
    VALUES (
		 @CEDPERS13
		,@CODSEGU14
		,@CODENFR15
		,@DESENFR16
		,@RECTRAT16
		,@DESTRAT16
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO


-- PASO 3: VIVIENDA
IF object_id('SP_INS_REGVIVI') IS NOT NULL DROP PROCEDURE SP_INS_REGVIVI
GO
CREATE PROCEDURE SP_INS_REGVIVI
		 @CODTIPV18 int
        ,@CODESTV19 int
        ,@CODMATE17 int
        ,@MTOVIVI20 decimal(18,4)
        ,@NAPVIVI20 varchar(20)
        ,@SRCVIVI20 varchar(2)
        ,@SRIVIVI20 varchar(2)
        ,@SRLVIVI20 varchar(2)
        ,@SRMVIVI20 varchar(2)
        ,@SRBVIVI20 varchar(2)
        ,@SREVIVI20 varchar(2)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_20REGVIVI
    (
		 CODTIPV18
		,CODESTV19
		,CODMATE17
		,MTOVIVI20
		,NAPVIVI20
		,SRCVIVI20
		,SRIVIVI20
		,SRLVIVI20
		,SRMVIVI20
		,SRBVIVI20
		,SREVIVI20
	)
    VALUES (
		 @CODTIPV18
		,@CODESTV19
		,@CODMATE17
		,@MTOVIVI20
		,@NAPVIVI20
		,@SRCVIVI20
		,@SRIVIVI20
		,@SRLVIVI20
		,@SRMVIVI20
		,@SRBVIVI20
		,@SREVIVI20
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO


-- PASO 4: PROBLEMAS SOCIALES
--IF object_id('SP_INS_REGASPS') IS NOT NULL DROP PROCEDURE SP_INS_REGASPS
--GO
--CREATE PROCEDURE SP_INS_REGASPS
--		 @CEDPERS13 varchar(20)
--		,@CODSEGU14 int
--		,@CODENFR15 int
--		,@DESENFR16 varchar(50)
--		,@RECTRAT16 varchar(2)
--		,@DESTRAT16 varchar(50)
--AS
--BEGIN
--BEGIN TRY
--	INSERT INTO dbo.SIDEPS_16REGASPS
--    (
--		 CEDPERS13
--		,CODSEGU14
--		,CODENFR15
--		,DESENFR16
--		,RECTRAT16
--		,DESTRAT16
--	)
--    VALUES
--	(
--		 @CEDPERS13
--		,@CODSEGU14
--		,@CODENFR15
--		,@DESENFR16
--		,@RECTRAT16
--		,@DESTRAT16
--	)

--	RETURN 0
--END TRY
--BEGIN CATCH
--	RETURN -1
--END CATCH
--END
--GO


-- PASO 5: SITUACION FINANCIERA
IF object_id('SP_INS_REGFAML') IS NOT NULL DROP PROCEDURE SP_INS_REGFAML
GO
CREATE PROCEDURE SP_INS_REGFAML
		 @CEDFAML22 varchar(20)
		,@NOMFAML22 varchar(50)
		,@EDAFAML22 int
		,@CODESTC06 int
		,@CODNEDU09 int
		,@OACFAML22 varchar(100)
		,@INGFAML22 decimal(18,4)
		,@DESFAML22 varchar(200)
		,@CODORGS21 int
		,@CODENFR15 int
		,@CODPARE12 int
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_22REGFAML
    (
		 CEDFAML22
		,NOMFAML22
		,EDAFAML22
		,CODESTC06
		,CODNEDU09
		,OACFAML22
		,INGFAML22
		,DESFAML22
		,CODORGS21
		,CODENFR15
		,CODPARE12
	)
    VALUES 
	(
		 @CEDFAML22
		,@NOMFAML22
		,@EDAFAML22
		,@CODESTC06
		,@CODNEDU09
		,@OACFAML22
		,@INGFAML22
		,@DESFAML22
		,@CODORGS21
		,@CODENFR15
		,@CODPARE12
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO


-- PASO 6: EGRESOS MENSUALES
IF object_id('SP_INS_REGEGRF') IS NOT NULL DROP PROCEDURE SP_INS_REGEGRF
GO
CREATE PROCEDURE SP_INS_REGEGRF
		 @MTOALQU24 decimal(18,4)
		,@MTOALIM24 decimal(18,4)
		,@MTOELEC24 decimal(18,4)
		,@MTOGAST24 decimal(18,4)
		,@MTCAGUA24 decimal(18,4)
		,@MTOCABL24 decimal(18,4)
		,@MTOTELF24 decimal(18,4)
		,@MTOINTE24 decimal(18,4)
		,@MTOEDUC24 decimal(18,4)
		,@MTOSEGU24 decimal(18,4)
		,@MTOOTRO24 decimal(18,4)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_24REGEGRF
    (
		 MTOALQU24
		,MTOALIM24
		,MTOELEC24
		,MTOGAST24
		,MTCAGUA24
		,MTOCABL24
		,MTOTELF24
		,MTOINTE24
		,MTOEDUC24
		,MTOSEGU24
		,MTOOTRO24
	)
    VALUES 
	(			
		 @MTOALQU24
		,@MTOALIM24
		,@MTOELEC24
		,@MTOGAST24
		,@MTCAGUA24
		,@MTOCABL24
		,@MTOTELF24
		,@MTOINTE24
		,@MTOEDUC24
		,@MTOSEGU24
		,@MTOOTRO24
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO


-- PASO 7: MOTIVO SOLICITUD
--IF object_id('SP_INS_') IS NOT NULL DROP PROCEDURE SP_INS_
--GO
--CREATE PROCEDURE SP_INS_
--	@PARAMS varchar(20),
--AS
--BEGIN
--BEGIN TRY
--	INSERT INTO dbo.TABLE
--    (
--			PARAMS
--	)
--    VALUES 
--	(
--			@PARAMS
--	)

--	RETURN 0
--END TRY
--BEGIN CATCH
--	RETURN -1
--END CATCH
--END
--GO

--	CREAR CASO
IF object_id('SP_INS_REGCASO') IS NOT NULL DROP PROCEDURE SP_INS_REGCASO
GO
CREATE PROCEDURE SP_INS_REGCASO
		 @CEDPERS13 varchar(20)
		,@CODASPS16 int
		,@CEDUSRO07 varchar(20)
		,@CODVIVI20 int
		,@CODEGRF24 int
		,@FEICASO25 datetime
		,@FEFCASO25 datetime
		,@DESCASO25 varchar(200)
		,@OPICASO25 varchar(200)
		,@ESTCASO25 varchar(20)
AS
BEGIN
BEGIN TRY
	INSERT INTO dbo.SIDEPS_25REGCASO
    (
		 CEDPERS13
		,CODASPS16
		,CEDUSRO07
		,CODVIVI20
		,CODEGRF24
		,FEICASO25
		,FEFCASO25
		,DESCASO25
		,OPICASO25
		,ESTCASO25
	)
    VALUES 
	(
		 @CEDPERS13
		,@CODASPS16
		,@CEDUSRO07
		,@CODVIVI20
		,@CODEGRF24
		,@FEICASO25
		,@FEFCASO25
		,@DESCASO25
		,@OPICASO25
		,@ESTCASO25
	)

	RETURN 0
END TRY
BEGIN CATCH
	RETURN -1
END CATCH
END
GO