//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_23CATFINA
    {
        public int CODFINA23 { get; set; }
        public string CEDFAML22 { get; set; }
        public string CEDPERS13 { get; set; }
    
        public virtual SIDEPS_13REGPERS SIDEPS_13REGPERS { get; set; }
        public virtual SIDEPS_22REGFAML SIDEPS_22REGFAML { get; set; }
    }
}
