//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_23CATFINA
    {
        public int CODFINA23 { get; set; }
        public string CEDFAML22 { get; set; }
        public string CEDPERS13 { get; set; }
    
        public virtual SIDEPS_13REGPERS SIDEPS_13REGPERS { get; set; }
        public virtual SIDEPS_22REGFAML SIDEPS_22REGFAML { get; set; }
    }
}
