//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_02CATPROV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_02CATPROV()
        {
            this.SIDEPS_03CATCANT = new HashSet<SIDEPS_03CATCANT>();
        }
    
        public int CODPROV02 { get; set; }
        public string NOMPROV02 { get; set; }
        public Nullable<int> CODPAIS01 { get; set; }
    
        public virtual SIDEPS_01CATPAIS SIDEPS_01CATPAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_03CATCANT> SIDEPS_03CATCANT { get; set; }
    }
}
