//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_07REGUSRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_07REGUSRO()
        {
            this.SIDEPS_08REGTELF = new HashSet<SIDEPS_08REGTELF>();
            this.SIDEPS_25REGCASO = new HashSet<SIDEPS_25REGCASO>();
        }
    
        public string CEDUSRO07 { get; set; }
        public string NOMUSRO07 { get; set; }
        public string PAPUSRO07 { get; set; }
        public string SAPUSRO07 { get; set; }
        public Nullable<int> CODCANT03 { get; set; }
        public Nullable<int> CODDIAC04 { get; set; }
        public Nullable<int> CODUSRO05 { get; set; }
        public string ESTUSRO07 { get; set; }
        public string DIRUSRO07 { get; set; }
        public string NACUSRO07 { get; set; }
        public string CNTUSRO07 { get; set; }
        public Nullable<System.DateTime> FEIUSRO07 { get; set; }
        public Nullable<System.DateTime> FEFUSRO07 { get; set; }
        public Nullable<System.DateTime> FENUSRO07 { get; set; }
    
        public virtual SIDEPS_03CATCANT SIDEPS_03CATCANT { get; set; }
        public virtual SIDEPS_04REGDIAC SIDEPS_04REGDIAC { get; set; }
        public virtual SIDEPS_05TIPUSRO SIDEPS_05TIPUSRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_08REGTELF> SIDEPS_08REGTELF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_25REGCASO> SIDEPS_25REGCASO { get; set; }
    }
}
