//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_08REGTELF
    {
        public int CODTELF08 { get; set; }
        public string CEDUSRO07 { get; set; }
        public string NUMTELF08 { get; set; }
    
        public virtual SIDEPS_07REGUSRO SIDEPS_07REGUSRO { get; set; }
    }
}
