//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_28REGHIS
    {
        public int CODHIST28 { get; set; }
        public Nullable<int> CODCASO25 { get; set; }
        public string DESCASO28 { get; set; }
        public string ESTCASO28 { get; set; }
        public Nullable<System.DateTime> FECCASO28 { get; set; }
        public Nullable<System.DateTime> FECACTU28 { get; set; }
    
        public virtual SIDEPS_25REGCASO SIDEPS_25REGCASO { get; set; }
    }
}
