//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_15CATENFR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_15CATENFR()
        {
            this.SIDEPS_16REGASPS = new HashSet<SIDEPS_16REGASPS>();
            this.SIDEPS_22REGFAML = new HashSet<SIDEPS_22REGFAML>();
        }
    
        public int CODENFR15 { get; set; }
        public string DESENFR15 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_16REGASPS> SIDEPS_16REGASPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_22REGFAML> SIDEPS_22REGFAML { get; set; }
    }
}
