//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_16REGASPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_16REGASPS()
        {
            this.SIDEPS_25REGCASO = new HashSet<SIDEPS_25REGCASO>();
        }
    
        public int CODASPS16 { get; set; }
        public string CEDPERS13 { get; set; }
        public Nullable<int> CODSEGU14 { get; set; }
        public Nullable<int> CODENFR15 { get; set; }
        public string DESENFR16 { get; set; }
        public string RECTRAT16 { get; set; }
        public string DESTRAT16 { get; set; }
    
        public virtual SIDEPS_13REGPERS SIDEPS_13REGPERS { get; set; }
        public virtual SIDEPS_14CATSEGU SIDEPS_14CATSEGU { get; set; }
        public virtual SIDEPS_15CATENFR SIDEPS_15CATENFR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_25REGCASO> SIDEPS_25REGCASO { get; set; }
    }
}
