//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_13REGPERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_13REGPERS()
        {
            this.SIDEPS_16REGASPS = new HashSet<SIDEPS_16REGASPS>();
            this.SIDEPS_23CATFINA = new HashSet<SIDEPS_23CATFINA>();
            this.SIDEPS_25REGCASO = new HashSet<SIDEPS_25REGCASO>();
        }
    
        public string CEDPERS13 { get; set; }
        public Nullable<int> CODESTC06 { get; set; }
        public Nullable<int> CODNEDU09 { get; set; }
        public Nullable<int> CODCANT03 { get; set; }
        public Nullable<int> CODSOLI10 { get; set; }
        public Nullable<int> CODRELG11 { get; set; }
        public string NOMPERS13 { get; set; }
        public string PAPPERS13 { get; set; }
        public string SAPPERS13 { get; set; }
        public string NACPERS13 { get; set; }
        public string DIRPERS13 { get; set; }
        public string OACPERS13 { get; set; }
        public string OANPERS13 { get; set; }
    
        public virtual SIDEPS_03CATCANT SIDEPS_03CATCANT { get; set; }
        public virtual SIDEPS_06CATESTC SIDEPS_06CATESTC { get; set; }
        public virtual SIDEPS_09CATNEDU SIDEPS_09CATNEDU { get; set; }
        public virtual SIDEPS_10CATSOLI SIDEPS_10CATSOLI { get; set; }
        public virtual SIDEPS_11CATRELG SIDEPS_11CATRELG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_16REGASPS> SIDEPS_16REGASPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_23CATFINA> SIDEPS_23CATFINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_25REGCASO> SIDEPS_25REGCASO { get; set; }
    }
}
