//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_25REGCASO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_25REGCASO()
        {
            this.SIDEPS_27TIPAYUD = new HashSet<SIDEPS_27TIPAYUD>();
            this.SIDEPS_28REGHIS = new HashSet<SIDEPS_28REGHIS>();
        }
    
        public int CODCASO25 { get; set; }
        public string CEDPERS13 { get; set; }
        public Nullable<int> CODASPS16 { get; set; }
        public string CEDUSRO07 { get; set; }
        public Nullable<int> CODVIVI20 { get; set; }
        public Nullable<int> CODEGRF24 { get; set; }
        public Nullable<System.DateTime> FEICASO25 { get; set; }
        public Nullable<System.DateTime> FEFCASO25 { get; set; }
        public string DESCASO25 { get; set; }
        public string OPICASO25 { get; set; }
        public string ESTCASO25 { get; set; }
    
        public virtual SIDEPS_07REGUSRO SIDEPS_07REGUSRO { get; set; }
        public virtual SIDEPS_13REGPERS SIDEPS_13REGPERS { get; set; }
        public virtual SIDEPS_16REGASPS SIDEPS_16REGASPS { get; set; }
        public virtual SIDEPS_20REGVIVI SIDEPS_20REGVIVI { get; set; }
        public virtual SIDEPS_24REGEGRF SIDEPS_24REGEGRF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_27TIPAYUD> SIDEPS_27TIPAYUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_28REGHIS> SIDEPS_28REGHIS { get; set; }
    }
}
