//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIDEPS_24REGEGRF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIDEPS_24REGEGRF()
        {
            this.SIDEPS_25REGCASO = new HashSet<SIDEPS_25REGCASO>();
        }
    
        public int CODEGRF24 { get; set; }
        public Nullable<decimal> MTOALQU24 { get; set; }
        public Nullable<decimal> MTOALIM24 { get; set; }
        public Nullable<decimal> MTOELEC24 { get; set; }
        public Nullable<decimal> MTOGAST24 { get; set; }
        public Nullable<decimal> MTCAGUA24 { get; set; }
        public Nullable<decimal> MTOCABL24 { get; set; }
        public Nullable<decimal> MTOTELF24 { get; set; }
        public Nullable<decimal> MTOINTE24 { get; set; }
        public Nullable<decimal> MTOEDUC24 { get; set; }
        public Nullable<decimal> MTOSEGU24 { get; set; }
        public Nullable<decimal> MTOOTRO24 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDEPS_25REGCASO> SIDEPS_25REGCASO { get; set; }
    }
}
