//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    
    public partial class SIDEPSEntidades : DbContext
    {
        public SIDEPSEntidades()
            : base("name=SIDEPSEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SIDEPS_01CATPAIS> SIDEPS_01CATPAIS { get; set; }
        public virtual DbSet<SIDEPS_02CATPROV> SIDEPS_02CATPROV { get; set; }
        public virtual DbSet<SIDEPS_03CATCANT> SIDEPS_03CATCANT { get; set; }
        public virtual DbSet<SIDEPS_04REGDIAC> SIDEPS_04REGDIAC { get; set; }
        public virtual DbSet<SIDEPS_05TIPUSRO> SIDEPS_05TIPUSRO { get; set; }
        public virtual DbSet<SIDEPS_06CATESTC> SIDEPS_06CATESTC { get; set; }
        public virtual DbSet<SIDEPS_07REGUSRO> SIDEPS_07REGUSRO { get; set; }
        public virtual DbSet<SIDEPS_08REGTELF> SIDEPS_08REGTELF { get; set; }
        public virtual DbSet<SIDEPS_09CATNEDU> SIDEPS_09CATNEDU { get; set; }
        public virtual DbSet<SIDEPS_10CATSOLI> SIDEPS_10CATSOLI { get; set; }
        public virtual DbSet<SIDEPS_11CATRELG> SIDEPS_11CATRELG { get; set; }
        public virtual DbSet<SIDEPS_12CATPARE> SIDEPS_12CATPARE { get; set; }
        public virtual DbSet<SIDEPS_13REGPERS> SIDEPS_13REGPERS { get; set; }
        public virtual DbSet<SIDEPS_14CATSEGU> SIDEPS_14CATSEGU { get; set; }
        public virtual DbSet<SIDEPS_15CATENFR> SIDEPS_15CATENFR { get; set; }
        public virtual DbSet<SIDEPS_16REGASPS> SIDEPS_16REGASPS { get; set; }
        public virtual DbSet<SIDEPS_17CATMATE> SIDEPS_17CATMATE { get; set; }
        public virtual DbSet<SIDEPS_18TIPVIVI> SIDEPS_18TIPVIVI { get; set; }
        public virtual DbSet<SIDEPS_19ESTVIVI> SIDEPS_19ESTVIVI { get; set; }
        public virtual DbSet<SIDEPS_20REGVIVI> SIDEPS_20REGVIVI { get; set; }
        public virtual DbSet<SIDEPS_21CATORGS> SIDEPS_21CATORGS { get; set; }
        public virtual DbSet<SIDEPS_22REGFAML> SIDEPS_22REGFAML { get; set; }
        public virtual DbSet<SIDEPS_23CATFINA> SIDEPS_23CATFINA { get; set; }
        public virtual DbSet<SIDEPS_24REGEGRF> SIDEPS_24REGEGRF { get; set; }
        public virtual DbSet<SIDEPS_25REGCASO> SIDEPS_25REGCASO { get; set; }
        public virtual DbSet<SIDEPS_26CATAYUD> SIDEPS_26CATAYUD { get; set; }
        public virtual DbSet<SIDEPS_27TIPAYUD> SIDEPS_27TIPAYUD { get; set; }
        public virtual DbSet<SIDEPS_28REGHIS> SIDEPS_28REGHIS { get; set; }
        public virtual DbSet<SIDEPS_29REGCNTR> SIDEPS_29REGCNTR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_CON_REGDIAC_Result> SP_CON_REGDIAC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CON_REGDIAC_Result>("SP_CON_REGDIAC");
        }
    
        public virtual ObjectResult<SP_CON_REGUSRO_Result> SP_CON_REGUSRO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CON_REGUSRO_Result>("SP_CON_REGUSRO");
        }
    
        public virtual ObjectResult<SP_CONXID_REGDIAC_Result> SP_CONXID_REGDIAC(Nullable<int> cODDIAC04)
        {
            var cODDIAC04Parameter = cODDIAC04.HasValue ?
                new ObjectParameter("CODDIAC04", cODDIAC04) :
                new ObjectParameter("CODDIAC04", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONXID_REGDIAC_Result>("SP_CONXID_REGDIAC", cODDIAC04Parameter);
        }
    
        public virtual ObjectResult<SP_CONXID_REGUSRO_Result> SP_CONXID_REGUSRO(Nullable<int> cEDUSRO07)
        {
            var cEDUSRO07Parameter = cEDUSRO07.HasValue ?
                new ObjectParameter("CEDUSRO07", cEDUSRO07) :
                new ObjectParameter("CEDUSRO07", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONXID_REGUSRO_Result>("SP_CONXID_REGUSRO", cEDUSRO07Parameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_DEL_REGDIAC(Nullable<int> cODDIAC04)
        {
            var cODDIAC04Parameter = cODDIAC04.HasValue ?
                new ObjectParameter("CODDIAC04", cODDIAC04) :
                new ObjectParameter("CODDIAC04", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DEL_REGDIAC", cODDIAC04Parameter);
        }
    
        public virtual int SP_DEL_REGUSRO(string cEDUSRO07)
        {
            var cEDUSRO07Parameter = cEDUSRO07 != null ?
                new ObjectParameter("CEDUSRO07", cEDUSRO07) :
                new ObjectParameter("CEDUSRO07", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DEL_REGUSRO", cEDUSRO07Parameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_INS_REGDIAC(string nOMDIAC04, string lUGDIAC04, string tELDIAC04, Nullable<int> cODCANT03)
        {
            var nOMDIAC04Parameter = nOMDIAC04 != null ?
                new ObjectParameter("NOMDIAC04", nOMDIAC04) :
                new ObjectParameter("NOMDIAC04", typeof(string));
    
            var lUGDIAC04Parameter = lUGDIAC04 != null ?
                new ObjectParameter("LUGDIAC04", lUGDIAC04) :
                new ObjectParameter("LUGDIAC04", typeof(string));
    
            var tELDIAC04Parameter = tELDIAC04 != null ?
                new ObjectParameter("TELDIAC04", tELDIAC04) :
                new ObjectParameter("TELDIAC04", typeof(string));
    
            var cODCANT03Parameter = cODCANT03.HasValue ?
                new ObjectParameter("CODCANT03", cODCANT03) :
                new ObjectParameter("CODCANT03", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGDIAC", nOMDIAC04Parameter, lUGDIAC04Parameter, tELDIAC04Parameter, cODCANT03Parameter);
        }
    
        public virtual int SP_INS_REGUSRO(string cEDUSRO07, string nOMUSRO07, string pAPUSRO07, string sAPUSRO07, Nullable<int> cODCANT03, Nullable<int> cODDIAC04, Nullable<int> cODUSRO05, string dIRUSRO07, string nACUSRO07, string cNTUSRO07, Nullable<System.DateTime> fENUSRO07)
        {
            var cEDUSRO07Parameter = cEDUSRO07 != null ?
                new ObjectParameter("CEDUSRO07", cEDUSRO07) :
                new ObjectParameter("CEDUSRO07", typeof(string));
    
            var nOMUSRO07Parameter = nOMUSRO07 != null ?
                new ObjectParameter("NOMUSRO07", nOMUSRO07) :
                new ObjectParameter("NOMUSRO07", typeof(string));
    
            var pAPUSRO07Parameter = pAPUSRO07 != null ?
                new ObjectParameter("PAPUSRO07", pAPUSRO07) :
                new ObjectParameter("PAPUSRO07", typeof(string));
    
            var sAPUSRO07Parameter = sAPUSRO07 != null ?
                new ObjectParameter("SAPUSRO07", sAPUSRO07) :
                new ObjectParameter("SAPUSRO07", typeof(string));
    
            var cODCANT03Parameter = cODCANT03.HasValue ?
                new ObjectParameter("CODCANT03", cODCANT03) :
                new ObjectParameter("CODCANT03", typeof(int));
    
            var cODDIAC04Parameter = cODDIAC04.HasValue ?
                new ObjectParameter("CODDIAC04", cODDIAC04) :
                new ObjectParameter("CODDIAC04", typeof(int));
    
            var cODUSRO05Parameter = cODUSRO05.HasValue ?
                new ObjectParameter("CODUSRO05", cODUSRO05) :
                new ObjectParameter("CODUSRO05", typeof(int));
    
            var dIRUSRO07Parameter = dIRUSRO07 != null ?
                new ObjectParameter("DIRUSRO07", dIRUSRO07) :
                new ObjectParameter("DIRUSRO07", typeof(string));
    
            var nACUSRO07Parameter = nACUSRO07 != null ?
                new ObjectParameter("NACUSRO07", nACUSRO07) :
                new ObjectParameter("NACUSRO07", typeof(string));
    
            var cNTUSRO07Parameter = cNTUSRO07 != null ?
                new ObjectParameter("CNTUSRO07", cNTUSRO07) :
                new ObjectParameter("CNTUSRO07", typeof(string));
    
            var fENUSRO07Parameter = fENUSRO07.HasValue ?
                new ObjectParameter("FENUSRO07", fENUSRO07) :
                new ObjectParameter("FENUSRO07", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REGUSRO", cEDUSRO07Parameter, nOMUSRO07Parameter, pAPUSRO07Parameter, sAPUSRO07Parameter, cODCANT03Parameter, cODDIAC04Parameter, cODUSRO05Parameter, dIRUSRO07Parameter, nACUSRO07Parameter, cNTUSRO07Parameter, fENUSRO07Parameter);
        }
    
        public virtual int SP_MOD_REGDIAC(Nullable<int> cODDIAC04, string nOMDIAC04, string lUGDIAC04, string tELDIAC04, string eSTDIAC04, Nullable<int> cODCANT03)
        {
            var cODDIAC04Parameter = cODDIAC04.HasValue ?
                new ObjectParameter("CODDIAC04", cODDIAC04) :
                new ObjectParameter("CODDIAC04", typeof(int));
    
            var nOMDIAC04Parameter = nOMDIAC04 != null ?
                new ObjectParameter("NOMDIAC04", nOMDIAC04) :
                new ObjectParameter("NOMDIAC04", typeof(string));
    
            var lUGDIAC04Parameter = lUGDIAC04 != null ?
                new ObjectParameter("LUGDIAC04", lUGDIAC04) :
                new ObjectParameter("LUGDIAC04", typeof(string));
    
            var tELDIAC04Parameter = tELDIAC04 != null ?
                new ObjectParameter("TELDIAC04", tELDIAC04) :
                new ObjectParameter("TELDIAC04", typeof(string));
    
            var eSTDIAC04Parameter = eSTDIAC04 != null ?
                new ObjectParameter("ESTDIAC04", eSTDIAC04) :
                new ObjectParameter("ESTDIAC04", typeof(string));
    
            var cODCANT03Parameter = cODCANT03.HasValue ?
                new ObjectParameter("CODCANT03", cODCANT03) :
                new ObjectParameter("CODCANT03", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MOD_REGDIAC", cODDIAC04Parameter, nOMDIAC04Parameter, lUGDIAC04Parameter, tELDIAC04Parameter, eSTDIAC04Parameter, cODCANT03Parameter);
        }
    
        public virtual int SP_MOD_REGUSRO(string cEDUSRO07, string nOMUSRO07, string pAPUSRO07, string sAPUSRO07, Nullable<int> cODCANT03, Nullable<int> cODDIAC04, Nullable<int> cODUSRO05, string eSTUSRO07, string dIRUSRO07, string nACUSRO07, string cNTUSRO07, Nullable<System.DateTime> fENUSRO07)
        {
            var cEDUSRO07Parameter = cEDUSRO07 != null ?
                new ObjectParameter("CEDUSRO07", cEDUSRO07) :
                new ObjectParameter("CEDUSRO07", typeof(string));
    
            var nOMUSRO07Parameter = nOMUSRO07 != null ?
                new ObjectParameter("NOMUSRO07", nOMUSRO07) :
                new ObjectParameter("NOMUSRO07", typeof(string));
    
            var pAPUSRO07Parameter = pAPUSRO07 != null ?
                new ObjectParameter("PAPUSRO07", pAPUSRO07) :
                new ObjectParameter("PAPUSRO07", typeof(string));
    
            var sAPUSRO07Parameter = sAPUSRO07 != null ?
                new ObjectParameter("SAPUSRO07", sAPUSRO07) :
                new ObjectParameter("SAPUSRO07", typeof(string));
    
            var cODCANT03Parameter = cODCANT03.HasValue ?
                new ObjectParameter("CODCANT03", cODCANT03) :
                new ObjectParameter("CODCANT03", typeof(int));
    
            var cODDIAC04Parameter = cODDIAC04.HasValue ?
                new ObjectParameter("CODDIAC04", cODDIAC04) :
                new ObjectParameter("CODDIAC04", typeof(int));
    
            var cODUSRO05Parameter = cODUSRO05.HasValue ?
                new ObjectParameter("CODUSRO05", cODUSRO05) :
                new ObjectParameter("CODUSRO05", typeof(int));
    
            var eSTUSRO07Parameter = eSTUSRO07 != null ?
                new ObjectParameter("ESTUSRO07", eSTUSRO07) :
                new ObjectParameter("ESTUSRO07", typeof(string));
    
            var dIRUSRO07Parameter = dIRUSRO07 != null ?
                new ObjectParameter("DIRUSRO07", dIRUSRO07) :
                new ObjectParameter("DIRUSRO07", typeof(string));
    
            var nACUSRO07Parameter = nACUSRO07 != null ?
                new ObjectParameter("NACUSRO07", nACUSRO07) :
                new ObjectParameter("NACUSRO07", typeof(string));
    
            var cNTUSRO07Parameter = cNTUSRO07 != null ?
                new ObjectParameter("CNTUSRO07", cNTUSRO07) :
                new ObjectParameter("CNTUSRO07", typeof(string));
    
            var fENUSRO07Parameter = fENUSRO07.HasValue ?
                new ObjectParameter("FENUSRO07", fENUSRO07) :
                new ObjectParameter("FENUSRO07", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MOD_REGUSRO", cEDUSRO07Parameter, nOMUSRO07Parameter, pAPUSRO07Parameter, sAPUSRO07Parameter, cODCANT03Parameter, cODDIAC04Parameter, cODUSRO05Parameter, eSTUSRO07Parameter, dIRUSRO07Parameter, nACUSRO07Parameter, cNTUSRO07Parameter, fENUSRO07Parameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
