//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcWebSIDEPS_2.srvUsuarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvUsuarios.IsrvUsuarios")]
    public interface IsrvUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/Usuario", ReplyAction="http://tempuri.org/IsrvUsuarios/UsuarioResponse")]
        System.Collections.Generic.List<Entidades.SIDEPS_07REGUSRO> Usuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/Usuario", ReplyAction="http://tempuri.org/IsrvUsuarios/UsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SIDEPS_07REGUSRO>> UsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/conUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/conUsuarioResponse")]
        System.Collections.Generic.List<Entidades.SP_CON_REGUSRO_Result> conUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/conUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/conUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_CON_REGUSRO_Result>> conUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/conUsuarioXId", ReplyAction="http://tempuri.org/IsrvUsuarios/conUsuarioXIdResponse")]
        Entidades.SP_CONXID_REGUSRO_Result conUsuarioXId(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/conUsuarioXId", ReplyAction="http://tempuri.org/IsrvUsuarios/conUsuarioXIdResponse")]
        System.Threading.Tasks.Task<Entidades.SP_CONXID_REGUSRO_Result> conUsuarioXIdAsync(int pid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/insUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/insUsuarioResponse")]
        bool insUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/insUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/insUsuarioResponse")]
        System.Threading.Tasks.Task<bool> insUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/modUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/modUsuarioResponse")]
        bool modUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/modUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/modUsuarioResponse")]
        System.Threading.Tasks.Task<bool> modUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/delUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/delUsuarioResponse")]
        bool delUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvUsuarios/delUsuario", ReplyAction="http://tempuri.org/IsrvUsuarios/delUsuarioResponse")]
        System.Threading.Tasks.Task<bool> delUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvUsuariosChannel : mvcWebSIDEPS_2.srvUsuarios.IsrvUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvUsuariosClient : System.ServiceModel.ClientBase<mvcWebSIDEPS_2.srvUsuarios.IsrvUsuarios>, mvcWebSIDEPS_2.srvUsuarios.IsrvUsuarios {
        
        public IsrvUsuariosClient() {
        }
        
        public IsrvUsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvUsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvUsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvUsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.SIDEPS_07REGUSRO> Usuario() {
            return base.Channel.Usuario();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SIDEPS_07REGUSRO>> UsuarioAsync() {
            return base.Channel.UsuarioAsync();
        }
        
        public System.Collections.Generic.List<Entidades.SP_CON_REGUSRO_Result> conUsuario() {
            return base.Channel.conUsuario();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SP_CON_REGUSRO_Result>> conUsuarioAsync() {
            return base.Channel.conUsuarioAsync();
        }
        
        public Entidades.SP_CONXID_REGUSRO_Result conUsuarioXId(int pid) {
            return base.Channel.conUsuarioXId(pid);
        }
        
        public System.Threading.Tasks.Task<Entidades.SP_CONXID_REGUSRO_Result> conUsuarioXIdAsync(int pid) {
            return base.Channel.conUsuarioXIdAsync(pid);
        }
        
        public bool insUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.insUsuario(pobjUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> insUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.insUsuarioAsync(pobjUsuario);
        }
        
        public bool modUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.modUsuario(pobjUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> modUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.modUsuarioAsync(pobjUsuario);
        }
        
        public bool delUsuario(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.delUsuario(pobjUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> delUsuarioAsync(Entidades.SIDEPS_07REGUSRO pobjUsuario) {
            return base.Channel.delUsuarioAsync(pobjUsuario);
        }
    }
}
